blog/urls.py
from django.urls import path, include

from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):


    class Status(models.TextChoices):
        DRAFT = 'DF', 'Черновик'
        PUBLISHED = 'PB', 'Опубликовано'


    title = models.CharField(max_length=250, verbose_name='Название')
    slug = models.SlugField(max_length=250, verbose_name='URL-блога', unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='Автор')
    body = models.TextField(verbose_name='Содержимое')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name='Статус')

    objects = models.Manager()
    published = PublishedManager()


    class Meta:
        ordering = ['-publish']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

        indexes = [models.Index(fields=['-publish'])]


    def __str__(self):
        return self.title
    

    def  get_absolute_url(self):
        return reverse('blog:post_detail', 
                       args=[self.publish.year, 
                             self.publish.month, 
                             self.publish.day,
                             self.slug])
    

class Comment(models.Model):
    post = models.ForeignKey(Post, 
                             on_delete=models.CASCADE, 
                             related_name='comments',
                             verbose_name='Пост')
    name = models.CharField(max_length=35, verbose_name='Имя')
    email = models.EmailField(verbose_name='Имеил')
    body = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', db_index=True)
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(widget=forms.Textarea, required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
#from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.views.decorators.http import require_POST


from .models import Post, Comment
from .forms import EmailPostForm, CommentForm


class PostListView(ListView):

    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/list.html'


def post_detail(request, year, month, day, post):
    print(request.method)
    post = get_object_or_404(Post, 
                             slug=post,
                             publish__day=day,
                             publish__month=month,
                             publish__year=year, 
                             status=Post.Status.PUBLISHED)
    
    comments = post.comments.filter(active=True)
    form = CommentForm()    

    return render(request, 'blog/detail.html', {'post': post, 'comments': comments, 'form': form})


def post_share(request, post_id):
    post = get_object_or_404(Post, pk=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            print(cd)
            post_url = request.build_absolute_uri(post.get_absolute_url())
            title = f'{cd["name"]} recommends you read {post.title}'
            message = f'{cd["name"]} recommends you read {post.title}. Go to {post_url}. Comment:\n{cd["comment"]}'
            send_mail(title, message, cd['email'], [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/share.html', {'post': post, 'form': form, 'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id, status=Post.Status.PUBLISHED)
    comment = None

    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        print(comment)
        comment.save()
    
    return render(request, 'blog/comment.html', {'post': post, 'form': form, 'comment': comment})

blog/templates/blog/comment.html
{% extends 'layout/basic.html' %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added</h2>
        <p><a href="{{ post.get_absolute_url }}" >Back to the post</a></p>
    {% else %}
        {% include 'layout/comment_form.html'%}
    {% endif %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'layout/basic.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|linebreaks }}

    <p>
    <a href="{% url 'blog:post_share' post.id %}">Share post</a>
    </p>

    {% with comments.count as total_comments %}
    <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet</a>
    {% endfor %}

    {% include 'layout/comment_form.html' %}

{% endblock %}

blog/templates/blog/list.html
{% extends 'layout/basic.html' %}

{% block title %}My blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
        </h2>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    {% include "layout/paginator.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/share.html
{% extends 'layout/basic.html' %}

{% block title %}Share post{% endblock %}

{% block content %}

    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>{{ post.title }} was successfully sent to {{ form.cleaned_data.to }}></p>
        <p><a href="{{ post.get_absolute_url }}">Go back</a></p>
    {% else %}
        <h1>Share {{ post.title }} by e-mail</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form>
    {% endif %}
{% endblock %}

blog/templates/layout/basic.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'blog/blog.css' %}">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog</p>
    </div>
</body>
</html>

blog/templates/layout/comment_form.html
<h2>Add a new comment</h2>
<form method="post" action="{% url 'blog:post_comment' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Add comment"></p>
</form>

blog/templates/layout/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>    
</div>